/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewPages;

import Model.Customer;
import Model.Order;
import Model.Shoe;
import Service.CustomerService;
import Service.EmployeeService;
import Service.OrderService1;
import Service.ShoeService;
import java.lang.reflect.Array;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Serge
 */
public class PlaceOrder extends javax.swing.JInternalFrame {
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        addTableColumnsHeader();
        addTableRowDataShoe();
    }
    private void addTableColumnsHeader(){
        tableModel.addColumn("Id");
        tableModel.addColumn("Name");
        tableModel.addColumn("Brand");
        tableModel.addColumn("Size");
        tableModel.addColumn("Price");
        shoeTable.setModel(tableModel);
    }
    
    private void addTableRowDataShoe(){
        try {
            tableModel.setRowCount(0);
            Registry thereg = LocateRegistry.getRegistry("127.0.0.1", 6000);
            ShoeService service = (ShoeService) thereg.lookup("shoe");
            List<Shoe> shoes = service.retrieveShoe();
            for(Shoe theshoe: shoes){
                tableModel.addRow(new Object[]{
                    theshoe.getShoeId(),
                    theshoe.getShoeName(),
                    theshoe.getBrand(),
                    theshoe.getShoeSize(),
                    theshoe.getPrice()
                        
//                thecustomers.getCust_phone()
                });
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ShoeMgt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ShoeMgt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//    List<Order>  orders = new ArrayList<>
//    void addRows(){
        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        shoeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchShoetxt = new javax.swing.JTextField();
        searchShoe = new javax.swing.JButton();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brandtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sizetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        contacttxt = new javax.swing.JTextField();
        searchCusttxt = new javax.swing.JTextField();
        searchCustomerBtn = new javax.swing.JButton();
        custIdtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        shoeIdtxt = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        shoeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(shoeTable);

        jLabel1.setText("Customer First Name:");

        jLabel2.setText("Shoe Name: ");

        registerBtn.setText("Place");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Update");

        jButton3.setText("Delete");

        searchShoe.setText("Search");
        searchShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchShoeActionPerformed(evt);
            }
        });

        jLabel4.setText("Brand:");

        jLabel5.setText("Price:");

        jLabel6.setText("Size:");

        jLabel7.setText("Customer Last Name:");

        jLabel8.setText("Phone:");

        searchCustomerBtn.setText("Search ");
        searchCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("CustId");

        jLabel10.setText("ShoeId");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchShoetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchShoe)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shoeIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(custIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(searchCusttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(searchCustomerBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(registerBtn)
                        .addGap(48, 48, 48)
                        .addComponent(jButton3)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(custIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCusttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCustomerBtn))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchShoe)
                    .addComponent(searchShoetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shoeIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(249, 249, 249))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
 try {
    if (fnametxt.getText().trim().isEmpty() || lnametxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first search for the Customer", "Empty Field", JOptionPane.ERROR_MESSAGE);
    } else if (nametxt.getText().trim().isEmpty() || brandtxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Search for Shoe", "Empty Field", JOptionPane.ERROR_MESSAGE);
    } else {
        // Initialize Order object
        Order order = new Order();

        // Create a Customer object with the given ID
        int customerId = Integer.parseInt(custIdtxt.getText().trim());
        Customer customer = new Customer();
        customer.setCustomerId(customerId);

        // Retrieve the Customer object
        Registry customerRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        CustomerService customerService = (CustomerService) customerRegistry.lookup("customer");
        Customer fetchedCustomer = customerService.searchCustomer(customer);
        if (fetchedCustomer == null) {
            JOptionPane.showMessageDialog(this, "Customer not found", "Invalid Customer ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        order.setCustomer(fetchedCustomer);

        // Create a Shoe object with the given ID
        int shoeId = Integer.parseInt(shoeIdtxt.getText().trim());
        Shoe shoe = new Shoe();
        shoe.setShoeId(shoeId);

        // Retrieve the Shoe object
        Registry shoeRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        ShoeService shoeService = (ShoeService) shoeRegistry.lookup("shoe");
        Shoe fetchedShoe = shoeService.searchShoe(shoe);
        if (fetchedShoe == null) {
            JOptionPane.showMessageDialog(this, "Shoe not found", "Invalid Shoe ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        order.setTheShoe(fetchedShoe);

        // Register the order
        Registry orderRegistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
        OrderService1 orderService = (OrderService1) orderRegistry.lookup("order");
        Order orderObj = orderService.registerOrder(order);

        if (orderObj != null) {
            JOptionPane.showMessageDialog(this, "Order registered", "Result", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Order not registered", "Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }
} catch (Exception e) {
    e.printStackTrace();
}


// TODO add your handling code here:

                // TODO add your handling code here:
        
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void searchShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchShoeActionPerformed
        try {
            if (searchShoetxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Id ", "Empty Field", JOptionPane.ERROR_MESSAGE);
        }
       // else if(searchtxt.getText().length() != 5){
       //     JOptionPane.showMessageDialog(this, "Id must be 5 characters ", "Length of Id Error", JOptionPane.ERROR_MESSAGE);
       // }
        else {
            // Assuming Employee is your model class
             Shoe shoe = new Shoe();
             Registry theregistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
            
            ShoeService service = (ShoeService) theregistry.lookup("shoe");

            shoe.setShoeId(Integer.parseInt(searchShoetxt.getText()));
            Shoe shoeObj = service.searchShoe(shoe);
            
            if (shoeObj == null) {
                JOptionPane.showMessageDialog(this, "Id does not Exist", "Result", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Populate data from the model to the text fields
                shoeIdtxt.setText(""+shoeObj.getShoeId());
                nametxt.setText(shoeObj.getShoeName());
                brandtxt.setText(shoeObj.getBrand());
             
                sizetxt.setText(""+shoeObj.getShoeSize());
                pricetxt.setText(""+shoeObj.getPrice());
                
                
                //registerBtn.setEnabled(false);
            }
        } 
        } catch (Exception e) {
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_searchShoeActionPerformed

    private void searchCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerBtnActionPerformed
        try {
            Customer customer = new Customer();
            Registry theregistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
            CustomerService service = (CustomerService) theregistry.lookup("customer");
            customer.setCustomerId(Integer.parseInt(searchCusttxt.getText()));
            Customer customerObj = service.searchCustomer(customer);
            if(customerObj == null){
                JOptionPane.showMessageDialog(this, "Id does not exist", "Invalid id", JOptionPane.ERROR_MESSAGE);
            }
            else{
                custIdtxt.setText(""+customerObj.getCustomerId());
                fnametxt.setText(customerObj.getFirstName());
                lnametxt.setText(customerObj.getLastName());
                contacttxt.setText(""+customerObj.getPhoneNumber());
                
            }
        } catch (Exception e) {
        }
     // TODO add your handling code here:
    }//GEN-LAST:event_searchCustomerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandtxt;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JTextField custIdtxt;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton searchCustomerBtn;
    private javax.swing.JTextField searchCusttxt;
    private javax.swing.JButton searchShoe;
    private javax.swing.JTextField searchShoetxt;
    private javax.swing.JTextField shoeIdtxt;
    private javax.swing.JTable shoeTable;
    private javax.swing.JTextField sizetxt;
    // End of variables declaration//GEN-END:variables
}

