/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewPages;

import Model.Shoe;
import Service.ShoeService;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Serge
 */
public class ShoeMgt extends javax.swing.JInternalFrame {
DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form ShoeMgt
     */
    public ShoeMgt() {
        initComponents();
        addTableColumnsHeader();
        addTableRowDataShoe();
    }
    
    private void addTableColumnsHeader(){
        tableModel.addColumn("Id");
        tableModel.addColumn("Name");
        tableModel.addColumn("Brand");
        tableModel.addColumn("Size");
        tableModel.addColumn("Price");
        ShoeTable.setModel(tableModel);
    }
    
    private void addTableRowDataShoe(){
        try {
            tableModel.setRowCount(0);
            Registry thereg = LocateRegistry.getRegistry("127.0.0.1", 6000);
            ShoeService service = (ShoeService) thereg.lookup("shoe");
            List<Shoe> shoes = service.retrieveShoe();
            for(Shoe theshoe: shoes){
                tableModel.addRow(new Object[]{
                    theshoe.getShoeId(),
                    theshoe.getShoeName(),
                    theshoe.getBrand(),
                    theshoe.getShoeSize(),
                    theshoe.getPrice()
                        
//                thecustomers.getCust_phone()
                });
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ShoeMgt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ShoeMgt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        brandtxt = new javax.swing.JTextField();
        sizetxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShoeTable = new javax.swing.JTable();
        searchtxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Shoe Name: ");

        jLabel2.setText("Brand:");

        jLabel3.setText("Size");

        jLabel4.setText("Price:");

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        ShoeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Brand", "Size", "Price"
            }
        ));
        ShoeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShoeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ShoeTable);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(searchBtn)
                .addGap(234, 234, 234))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(registerBtn)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerBtn)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(567, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        if(nametxt.getText().trim().isEmpty() || brandtxt.getText().trim().isEmpty()){
              JOptionPane.showMessageDialog(this, "Fill in all fields","Invalid input", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
            Shoe shoe = new Shoe();
            shoe.setShoeName(nametxt.getText());
            shoe.setBrand(brandtxt.getText());
            shoe.setShoeSize(Integer.parseInt(sizetxt.getText()));
            shoe.setPrice(Double.parseDouble(pricetxt.getText()));

            Registry thereg = LocateRegistry.getRegistry("127.0.0.1", 6000);
            ShoeService service = (ShoeService) thereg.lookup("shoe");
            Shoe shoeObj = service.registerShoe(shoe);
            if (shoeObj != null) {
                JOptionPane.showMessageDialog(this, "Data inserted", "Result", JOptionPane.INFORMATION_MESSAGE);
            addTableRowDataShoe();
            } else {
                JOptionPane.showMessageDialog(this, "Data not Inserted", "Result", JOptionPane.ERROR_MESSAGE);
            }
            

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_registerBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
          Registry thereg = LocateRegistry.getRegistry("127.0.0.1", 6000);
          ShoeService service = (ShoeService) thereg.lookup("shoe");
          Shoe shoe = new Shoe();
          shoe.setShoeId(Integer.parseInt(searchtxt.getText()));
          Shoe shoeObj = service.deleteShoe(shoe);
          if(shoeObj == null){
              JOptionPane.showMessageDialog(this, "Data not deleted","Result",JOptionPane.ERROR_MESSAGE);
          }
          else{
              JOptionPane.showMessageDialog(this, "Data deleted","Result",JOptionPane.INFORMATION_MESSAGE);
          }
        //    }
            
     } catch (Exception e) {
         e.printStackTrace();
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
        if (searchtxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Id ", "Empty Field", JOptionPane.ERROR_MESSAGE);
        }
       // else if(searchtxt.getText().length() != 5){
       //     JOptionPane.showMessageDialog(this, "Id must be 5 characters ", "Length of Id Error", JOptionPane.ERROR_MESSAGE);
       // }
        else {
            // Assuming Employee is your model class
            Shoe shoe = new Shoe();
             Registry theregistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
            
            ShoeService service = (ShoeService) theregistry.lookup("shoe");

            shoe.setShoeId(Integer.parseInt(searchtxt.getText()));
            Shoe shoeObj = service.searchShoe(shoe);
            
            if (shoeObj == null) {
                JOptionPane.showMessageDialog(this, "Id does not Exist", "Result", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Populate data from the model to the text fields
                
                nametxt.setText(shoeObj.getShoeName());
                brandtxt.setText(shoeObj.getBrand());
             
                sizetxt.setText(""+shoeObj.getShoeSize());
                pricetxt.setText(""+shoeObj.getPrice());
                
                
                registerBtn.setEnabled(false);
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }                // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                
        int selectedRow = ShoeTable.getSelectedRow();
        DefaultTableModel tbModel = (DefaultTableModel) ShoeTable.getModel();
        int theId = Integer.parseInt(tbModel.getValueAt(selectedRow,0).toString());
        
        Shoe sh = new Shoe();
        
        sh.setShoeId(theId);
        
        sh.setShoeName(nametxt.getText());
        sh.setBrand(brandtxt.getText());
        sh.setShoeSize(Integer.parseInt(sizetxt.getText()));
        sh.setPrice(Double.parseDouble(pricetxt.getText()));
        
        try {
            Registry theregistry = LocateRegistry.getRegistry("127.0.0.1", 6000);
            
            ShoeService service = (ShoeService) theregistry.lookup("shoe");

//            shoe.setShoeId(Integer.parseInt(searchtxt.getText()));
            Shoe shoeObj = service.updateShoe(sh);
            if (shoeObj != null){
            JOptionPane.showMessageDialog(this, "shoe updated");
            addTableRowDataShoe();
            nametxt.setText("");
            brandtxt.setText("");
            sizetxt.setText("");
            pricetxt.setText("");
            }else{
            JOptionPane.showMessageDialog(this, "shoe not updated");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ShoeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShoeTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = ShoeTable.getSelectedRow();
        DefaultTableModel tbModel = (DefaultTableModel) ShoeTable.getModel();
        nametxt.setText(tbModel.getValueAt(selectedRow, 1).toString());
        brandtxt.setText(tbModel.getValueAt(selectedRow, 2).toString());
        sizetxt.setText(tbModel.getValueAt(selectedRow, 3).toString());
        pricetxt.setText(tbModel.getValueAt(selectedRow, 4).toString());
        
    }//GEN-LAST:event_ShoeTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShoeTable;
    private javax.swing.JTextField brandtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField sizetxt;
    // End of variables declaration//GEN-END:variables
}
